"""Column-level configuration constants for vin_candidates transformation."""

COLUMNS_TO_DROP = [
    "row_id",
    "new_potentialforacceleratedorconditionalregulator",
    "crc8b_updatedforipps20",
    "vin_stringentregulatoryauthoritysraapprovalda",
    "vin_includeinevgendatabase",
    "new_platform",
    "new_personslivingwithhiv",
    "vin_id",
    "crc8b_ghtcroireviewstatus",
    "vin_2019candidateidnumber",
    "new_medicated",
    "crc8b_ndpipelinereviewstatus",
    "vin_numberofcountrieswithproductapproval_date",
    "vin_casnumber",
    "new_exportgroup",
    "crc8b_ndpipelinereviewdate",
    "new_pipscomments",
    "new_adjuvantrequirement",
    "new_whreviewdate",
    "_modifiedby_value",
    "vin_reviewpersonaggregated",
    "vin_iggformatanimalderived",
    "new_durationofaction",
    "new_reviewstatus",
    "vin_fdapregnancylabelingpregnancyrisksummary",
    "new_regionofregistration",
    "new_estimateddateofregulatoryfiling",
    "vin_regionspecificityaggregated",
    "vin_sbereviewdate",
    "new_2023includeinevgendatabase",
    "vin_evgenreviewcompleted",
    "timezoneruleversionnumber",
    "new_aim1clinicalusestatus",
    "new_updatedforaim20",
    "new_includeinaim1",
    "_createdby_value",
    "vin_evgenreviewdate",
    "crc8b_includeinipps20",
    "new_thermostabilityandstorage",
    "new_atcclassification",
    "vin_meshheadings",
    "vin_directactionontoxins",
    "vin_duplicateentrycapformorethanonedisease",
    "importsequencenumber",
    "crc8b_srhreviewdate",
    "createdon",
    "statuscode",
    "crc8b_updatedforndpipeline",
    "vin_2019archetype",
    "vin_nationalregulatoryauthorityapprovaldate",
    "new_tppreviewrequired",
    "vin_otherindications",
    "vin_includeinwellcomesbedatabase",
    "new_includeinportal2025",
    "new_aim1archetype",
    "new_reviewdateipps30",
    "new_chimstudyyesno",
    "vin_productiontechniqueandorimmunizationstrat",
    "new_ipps30reviewstatus",
    "vin_reviewnotes",
    "new_profilestatus",
    "vin_adisid",
    "new_mamedicinesubtype",
    "crc8b_includeinghtcroi",
    "new_includeinwhpipeline",
    "vin_2019pcrpipelineinclusion",
    "vin_adisurl",
    "new_ctregistrylink2",
    "_owninguser_value",
    "vin_2019disease",
    "crc8b_platformtechnologyused",
    "new_dateforstream",
    "_vin_pipct_value",
    "new_reviewdate",
    "new_cttitle",
    "new_includeinipps30",
    "vin_ifyesdoesclinicaltrialevidencepredate2015",
    "vin_2019product",
    "new_snakespecies_producttestedin",
    "new_safetyandreactogenicityprofile",
    "new_pesubtype",
    "crc8b_descriptionofipps20update",
    "new_exportorder",
    "new_updatedforipps30",
    "vin_syndromicprofiles",
    "vin_routeofadministrationaggregated",
    "new_safetyreactogenicityprofile",
    "vin_isthereevidencethatthecandidatehasbeentes",
    "_vin_archetype_value",
    "new_clinicaltrialgeographicallocation",
    "vin_2019candidatename",
    "crc8b_srhprofilestatus",
    "new_includeinaim2",
    "vin_2019complexitysecondpass",
    "crc8b_includeinippscdf",
    "new_aim1pcrreviewnotes",
    "vin_inactivedevelopmenttype",
    "new_impactmodellingurl",
    "new_aim1devstatus",
    "new_2024includeinpipeline",
    "vin_countryspecificityaggregated",
    "new_whprofilestatus",
    "new_efficacyandclinicalendpoints",
    "new_aim1identifier",
    "crc8b_originofipps20update",
    "vin_2019subdisease",
    "vin_stringentregulatoryauthoritysraapproval",
    "new_aim1highestrdstage",
    "crc8b_includeinndpipeline",
    "_new_numberofcts_value",
    "vin_2019status",
    "_ownerid_value",
    "crc8b_includeinsrhpipeline",
    "new_whereistheresearchlocated",
    "vin_ifigformatrecombinantotherpleasespecify",
    "crc8b_ipps20reviewstatus",
    "vin_iggformatrecombinant",
    "new_ctregistrylink3",
    "vin_includeinp2imodel",
    "new_includeinpipeline2021",
    "json_response",
    "sync_time",
    "vin_igfinalproducttypepreparationifapplicable",
    "crc8b_includeinipps10",
    "new_aim1currentrdstage",
    "new_treatmentregvxschedule",
    "new_isthisproductspecifictoaregion",
    "_owningbusinessunit_value",
    "new_interactionwithotherpharmacologicalproducts",
    "_vin_clinicalusestatus_value",
    "_vin_currentrndstage_value",
]

COLUMN_RENAMES = {
    "vin_name": "candidate_name",
    "new_sbereviewstatus": "sbereviewstatus",
    "vin_targettoxinclass": "targettoxinclass",
    "vin_knownfundersaggregated": "knownfundersaggregated",
    "new_vin_whosnakespeciesriskcatagainst": "whosnakespeciesriskcatagainst",
    "vin_approvalstatus": "approvalstatus",
    "vin_venomspecificity": "venomspecificity",
    "new_pressuretype": "pressuretype",
    "new_ctregistrylink": "ctregistrylink",
    "vin_approvedforuseinpregnantorlactatingwomen": "approvedforuseinpregnantorlactatingwomen",
    "new_technologyprinciple": "technologyprinciple",
    "new_ctenddate": "ctenddate",
    "vin_2019developers": "2019developers",
    "vin_usfdaapprovaldate": "usfdaapprovaldate",
    "vin_alternativenames": "alternativenames",
    "vin_product": "product",
    "vin_researchedinpregnantwomenorlactatingwomen": "researchedinpregnantwomenorlactatingwomen",
    "vin_target": "target",
    "vin_emaapprovalstatus": "emaapprovalstatus",
    "vin_inactivedevelopmentreason": "inactivedevelopmentreason",
    "new_2024knownfunders": "2024knownfunders",
    "vin_emaapprovaldate": "emaapprovaldate",
    "vin_previouslyidentifiedcandidate": "previouslyidentifiedcandidate",
    "new_2023knownfundersaggregated": "2023knownfunders",
    "crc8b_srhindication": "WH_indication",
    "vin_developersaggregated": "developersaggregated",
    "vin_japanesemhlwapprovalstatus": "japanesemhlwapprovalstatus",
    "vin_typeofpreclinicalresults": "typeofpreclinicalresults",
    "vin_stringentregulatoryauthorityapproval": "SRA_approvalstatus",
    "vin_whoprequalificationdate": "whoprequalificationdate",
    "vin_technologytype": "technologytype",
    "new_snakespeciesagainst": "snakespeciesagainst",
    "vin_numberofcountrieswithproductapproval": "numberofcountrieswithproductapproval",
    "new_developers2025": "developers2025",
    "vin_indication": "indication",
    "vin_snakespecies": "snakespecies",
    "vin_specifictargettoxinclass": "specifictargettoxinclass",
    "new_ctstartdate": "ctstartdate",
    "vin_chemicalname": "chemicalname",
    "vin_specimentype": "specimentype",
    "new_indicationtype": "indicationtype",
    "vin_mechanismofaction": "mechanismofaction",
    "vin_recentupdates": "recentupdates",
    "new_knownfunders2025": "knownfunders2025",
    "vin_usfdaapprovalstatus": "usfdaapprovalstatus",
    "vin_preclinicalresultsstatus": "preclinicalresultsstatus",
    "new_2023developersaggregated": "2023developersaggregated",
    "new_anticipatedsranraandwhopqstrategy": "anticipatedwhostrategy",
    "vin_whoprequalification": "whoprequalification",
    "new_2024developersaggregated": "2024developersaggregated",
    "vin_healthcarefacilitylevel": "healthcarefacilitylevel",
    "_vin_captype_value": "captype_value",
    "_vin_mainproduct_value": "mainproduct_value",
    "_vin_subproduct_value": "subproduct_value",
    "_vin_secondarydisease_value": "secondarydisease_value",
    "new_snakespeciesproductderivedfrom": "snakespeciesproductderivedfrom",
    "vin_keyfeatureschallenges": "keyfeatureschallenges",
    "new_agespecific": "agespecific",
    "new_testformat": "testformat",
    "vin_candidateid": "candidateid",
    "new_whoimmunizingspecies": "whoimmunizingspecies",
    "vin_japanesemhlwapprovaldate": "japanesemhlwapprovaldate",
    "vin_developmentstatus": "developmentstatus",
    "vin_snakefamily": "snakefamily",
    "vin_otherstringentregulatoryauthoritydate": "otherSRAdate",
    "vin_nationalregulatoryauthorityapprovalstatus": "NRAapprovalstatus",
    "new_2024developmentstatus": "2024developmentstatus",
    "_vin_disease_value": "diseasevalue",
    "new_includeinpipeline": "includeinpipeline",
    "vin_whosnakespeciesriskcategory": "whosnakespeciesriskcategory",
    "vin_preclinicalresultssource": "preclinicalresultssource",
    "vin_countrieswhereproductisapprovedaggregated": "countries_product_approved",
    "new_whoparaspecificityspecies": "whoparaspecificityspecies",
    "vin_thermostability": "thermostability",
    "new_peseverity": "peseverity",
    "new_2023developmentstatus": "2023developmentstatus",
    "_vin_currentrndstage_value": "rdstage_value",
    "vin_approvingauthority": "approvingauthority",
    "vin_2019stagepcr": "2019RDstage",
}
